name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main   # 这里改成你项目的默认分支
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # 1. 拉取代码
      - name: Checkout
        uses: actions/checkout@v3

      # 2. 安装 Node.js（指定 20 或 22，推荐 20 LTS）
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. 安装依赖
      - name: Install dependencies
        run: npm install

      # 4. 构建 Vite 项目（输出在 dist/）
      - name: Build
        run: npm run build

      # 5. 部署到 Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: "/"         # app 根目录
          api_location: ""          # 没有 API 就留空
          output_location: "build"   
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
